

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: smartgrid-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./infra/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./volumes/mosquitto:/mosquitto/data
    restart: unless-stopped
    networks:
      - smartgrid-network


networks:
  smartgrid-network:
    driver: bridge

